# Generated by Django 4.1 on 2023-10-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_movie_description_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
